### ISSUE TITLE
Required Fields Validation

### ISSUE THREAD

**Issue by parth-dassana** [dassana-io/dassana#475]
In both the run and validate APIs we want to ensure that the following fields are ALWAYS normalized when processing an alert:

- CSP
- Resource container
- Vendor ID
- Alert ID

#### ToDo's

- [ ] Modify run process to ensure above fields are populated once normalized workflow is done. 
- [ ] Need to ensure normalize workflow output  has the above required fields. 
- [ ] Change validation API to throw an error instead of a warning.
