### ISSUE TITLE
Enterprise billing - Stripe

### ISSUE THREAD

**Issue by hk-dassana** [dassana-io/dassana#542]
**We are starting to code for the billing component of our Enterprise product.**

This will utilize Stripe's APIs. ([https://stripe.com/docs/api](url))

Can reference below code from Parth's POC written in node:
[https://github.com/dassana-io/api-stripe-poc](url) 
[https://github.com/dassana-io/web-stripe-poc](url)

#### ToDos:
- [ ]   Learn stripe

- [ ]   Choose either Java or node 

- [ ]   Create a repo in billing

- [ ]   Code for the following functionalities:
  1. When customers sign up for our services, automatically create a user on stripe.
  2. Once user is created, create a product & subscription for the user.
  3. Be able to calculate and send usage for the user back to stripe to calculate billing cost.
